version: "3.9"

services:
  server1:
    build:
      context: ./server1
      dockerfile: ../Dockerfile
    ports:
      - "8001:8000"

  server2:
    build:
      context: ./server2
      dockerfile: ../Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - server1